services:
  - type: cron
    name: gravador-de-lives-nerd
    plan: free
    dockerfilePath: Dockerfile
    schedule: "30 22 * * 5,6,0"
    envGroups:
      - name: gravador-secrets
    secretFiles:
      - key: drive_config
        path: /rclone-secrets/drive_config
